import { cookieStorage, createStorage } from 'wagmi'
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi'
import { mainnet, arbitrum } from '@reown/appkit/networks'
import { soneiumMinato } from './chains'
import type { Chain } from 'viem'

// Read Project ID from environment variables
// Using NEXT_PUBLIC_PROJECT_ID based on reown-appkit.md.
// Ensure this matches your .env.local setup.
export const projectId = process.env.NEXT_PUBLIC_PROJECT_ID

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error('NEXT_PUBLIC_PROJECT_ID is not defined. Please set it in .env.local')
}

// Define supported networks, explicitly typed as a non-empty array of Chains
export const networks: [Chain, ...Chain[]] = [mainnet, arbitrum, soneiumMinato]

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }), // Use cookieStorage for SSR
  ssr: true, // Enable SSR support
  projectId,
  networks, // Pass the explicitly typed networks array
})

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig

// Get projectId from https://cloud.reown.com
export const projectIdFromReown = process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID

if (!projectIdFromReown) {
  throw new Error('Project ID is not defined in .env.local')
}

export const networksFromReown = [mainnet, arbitrum, soneiumMinato]

// Set up the Wagmi Adapter (Config)
export const wagmiAdapterFromReown = new WagmiAdapter({
  // Using cookieStorage for SSR compatibility
  storage: createStorage({
    storage: cookieStorage
  }),
  ssr: true, // Enable SSR support
  projectId: projectIdFromReown,
  networks: networksFromReown
})

// Export the underlying wagmi config for the WagmiProvider
export const wagmiConfigFromReown = wagmiAdapterFromReown.wagmiConfig 